dataSources:
  db_master: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.105:3306/gmall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  db_slave01: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.105:3316/gmall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
masterSlaveRule:
  name: db_ms_rule
  masterDataSourceName: db_master       #名字可以自定义
  slaveDataSourceNames: [db_slave01]    #多个slave,用逗号分隔！！
